---

# Primary RKE2 agent configuration parameters. Remove the curly braces ( {} ) and add your configuration.
# See https://docs.rke2.io/install/install_options/linux_agent_config/ for all configuration options.
rke2_config: {}
  # debug: false

rke2_config:
  selinux: true

  node-label: 
  - "kubernetes.io/hostname=rke2-worker"
  - "longhorn.node=true"


# (data) Folder to hold state (default: "/var/lib/rancher/rke2") 
#  data-dir: "/opt/rancher/rke2"

# See https://docs.rke2.io/install/containerd_registry_configuration/
# Add a registry configuration file by specifying the file path on the control host
# registry_config_file_path: "{{ playbook_dir }}/sample_files/registries.yaml"
